### ISSUE TITLE
Tables not rendering in PDF

### ISSUE THREAD

**Issue by michelspeiser** [rstudio/bookdown#1352] opened 2022-06-23 09:13 UTC
I am able to build a HTML book from RStudio, using Addins -> Preview Book, 
and it looks fine.

However if I build a PDF with:

```
bookdown::render_book(output_format = bookdown::pdf_book())
```

In the resulting PDF, where the table should be, there are two nearly blank pages with some odd symbols:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/62718868/175261372-242e1b62-93a1-406d-b16a-62d0f07ec915.png">

<img width="706" alt="image" src="https://user-images.githubusercontent.com/62718868/175263031-c7cedbe4-265c-4f7f-9598-d4e51460e612.png">

The rest of the PDF seems to be ok. The same happens if I use `pdf_document2`, and whether I choose a 'gitbook' or 'bs4_book' project.

Session info:

```
> xfun::session_info("bookdown")
R version 4.1.2 (2021-11-01)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7, RStudio 2022.2.3.492

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3 bookdown_0.27   bslib_0.3.1     digest_0.6.28  
  evaluate_0.15   fastmap_1.1.0   fs_1.5.2        glue_1.5.0     
  graphics_4.1.2  grDevices_4.1.2 highr_0.9       htmltools_0.5.2
  jquerylib_0.1.4 jsonlite_1.7.2  knitr_1.39      magrittr_2.0.1 
  methods_4.1.2   R6_2.5.1        rappdirs_0.3.3  rlang_0.4.12   
  rmarkdown_2.14  sass_0.4.1      stats_4.1.2     stringi_1.7.5  
  stringr_1.4.0   tinytex_0.40    tools_4.1.2     utils_4.1.2    
  xfun_0.31       yaml_2.2.1     

```

Full output:

```
> bookdown::render_book(output_format = bookdown::pdf_book())
Rendering book in directory '.'


processing file: index.Rmd
  |........                                          |  17%
   inline R code fragments

  |.................                                 |  33%
label: unnamed-chunk-1 (with options) 
List of 1
 $ eval: logi FALSE

  |.........................                         |  50%
  ordinary text without R code

  |.................................                 |  67%
label: unnamed-chunk-2 (with options) 
List of 1
 $ eval: logi FALSE

  |..........................................        |  83%
  ordinary text without R code

  |..................................................| 100%
label: unnamed-chunk-3 (with options) 
List of 1
 $ include: logi FALSE


output file: index.knit.md



processing file: 01-intro.Rmd
  |..................................................| 100%
  ordinary text without R code


output file: 01-intro.knit.md



processing file: 02-cross-refs.Rmd
  |............                                      |  25%
  ordinary text without R code

  |.........................                         |  50%
label: nice-fig (with options) 
List of 5
 $ fig.cap  : chr "Here is a nice figure!"
 $ out.width: chr "80%"
 $ fig.asp  : num 0.75
 $ fig.align: chr "center"
 $ fig.alt  : chr "Plot with connected points showing that vapor pressure of mercury increases exponentially as temperature increases."

  |......................................            |  75%
  ordinary text without R code

  |..................................................| 100%
label: nice-tab (with options) 
List of 1
 $ tidy: logi FALSE


output file: 02-cross-refs.knit.md



processing file: 03-parts.Rmd
  |..................................................| 100%
  ordinary text without R code


output file: 03-parts.knit.md



processing file: 04-citations.Rmd
  |..................................................| 100%
  ordinary text without R code


output file: 04-citations.knit.md



processing file: 05-blocks.Rmd
  |.................                                 |  33%
  ordinary text without R code

  |.................................                 |  67%
label: unnamed-chunk-1 (with options) 
List of 1
 $ collapse: logi TRUE

  |..................................................| 100%
  ordinary text without R code


output file: 05-blocks.knit.md



processing file: 06-share.Rmd
  |.................                                 |  33%
  ordinary text without R code

  |.................................                 |  67%
label: unnamed-chunk-1 (with options) 
List of 1
 $ eval: logi FALSE

  |..................................................| 100%
  ordinary text without R code


output file: 06-share.knit.md



processing file: 07-references.Rmd
  |..................................................| 100%
   inline R code fragments


output file: 07-references.knit.md

/Applications/RStudio.app/Contents/MacOS/quarto/bin/pandoc +RTS -K512m -RTS hello_bookdown.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash --output hello_bookdown.tex --lua-filter /Library/Frameworks/R.framework/Versions/4.1/Resources/library/bookdown/rmarkdown/lua/custom-environment.lua --lua-filter /Library/Frameworks/R.framework/Versions/4.1/Resources/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /Library/Frameworks/R.framework/Versions/4.1/Resources/library/rmarkdown/rmarkdown/lua/latex-div.lua --metadata-file /var/folders/1y/mz55z62j2zq07mktg94rf6qr0000gn/T//RtmpLcx8Kl/file6ce72b9f1dbc --self-contained --table-of-contents --toc-depth 2 --number-sections --highlight-style tango --pdf-engine pdflatex --variable graphics --wrap preserve --variable tables=yes --standalone -Mhas-frontmatter=false --citeproc 
Warning: LaTeX Warning: Reference `tab:nice-tab' on page 9 undefined on input line 286.
Warning: LaTeX Warning: There were undefined references.

Output created: _book/hello_bookdown.pdf
[1] "/Users/msp/Documents/hello_bookdown/hello_bookdown/_book/hello_bookdown.pdf"
/Applications/RStudio.app/Contents/MacOS/quarto/bin/pandoc +RTS -K512m -RTS ai4ers_bs4.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output ai4ers_bs4.html --lua-filter /Library/Frameworks/R.framework/Versions/4.1/Resources/library/bookdown/rmarkdown/lua/custom-environment.lua --lua-filter /Library/Frameworks/R.framework/Versions/4.1/Resources/library/rmarkdown/rmarkdown/lua/pagebreak.lua --lua-filter /Library/Frameworks/R.framework/Versions/4.1/Resources/library/rmarkdown/rmarkdown/lua/latex-div.lua --metadata-file /var/folders/1y/mz55z62j2zq07mktg94rf6qr0000gn/T//RtmpLcx8Kl/file6ce72030145c --wrap preserve --standalone --section-divs --template /Library/Frameworks/R.framework/Versions/4.1/Resources/library/bookdown/templates/bs4_book.html --highlight-style pygments --number-sections --css style.css --mathjax --include-in-header /var/folders/1y/mz55z62j2zq07mktg94rf6qr0000gn/T//RtmpLcx8Kl/rmarkdown-str6ce73488b486.html --citeproc 

Output created: _book/index.html
```

**Comment by cderv** [comment] 2022-06-23 09:16
> In the resulting PDF, where the table should be, there are two nearly blank pages with some odd symbols:

what is inside the document ? What is the code that creates the table ?

**Comment by michelspeiser** [comment] 2022-06-23 09:19
> what is inside the document ? What is the code that creates the table ?

It is the unmodified sample book I get when creating a new book project in RStudio.

The code pertaining to the table is as follows:

```{r nice-tab, tidy=FALSE}
knitr::kable(
  head(pressure, 10), caption = 'Here is a nice table!',
  booktabs = TRUE
)
```

**Comment by cderv** [comment] 2022-06-23 10:22
Ok, I got a more minimal reproducible example

````markdown
--- 
title: "A Minimal Book Example"
documentclass: book
author: "John Doe"
date: "23/06/2022"
---

# caption

```{r}
knitr::kable(head(pressure, 10), caption = "test")
```

# no caption

```{r}
knitr::kable(head(pressure, 10))
```
````

Adding a caption to the table, when using `documentclass: book` will create the issue. Remove one or the other and it should work. 

By comparing the TeX files, it seems `microtype` is causing the issue somehow. 

Can you try removing `microtype` package and then render the book ? 

You can add such chunk in `index.Rmd` supposing you are using TeX Live

````markdown
```{r}
if (tinytex::check_installed("microtype")) tinytex::tlmgr_remove("microtype")
```
````

You can also call this in your R console. 

Does it works correctly after this ? It solves the issue on my side. 

It seems to be a LaTeX issue with **microtype** package conflicting with tables in documentclass `book`

**Comment by cderv** [comment] 2022-06-23 10:42
I opened an issue in microtype to dig deeper 
https://github.com/schlcht/microtype/issues/20

**Comment by cderv** [comment] 2022-06-23 11:59
It seems like this is fixed in dev version - the maintainer will push a new version to CTAN shortly: https://github.com/schlcht/microtype/issues/20#issuecomment-1164286783

**Comment by michelspeiser** [comment] 2022-06-23 13:24
open source FTW!

**Comment by cderv** [comment] 2022-06-24 18:24
It is now working ok with the latest version of **microtype** release on CTAN!

**Closed by cderv** 2022-06-24 18:24 UTC
Labels: bug, tinytex
