### ISSUE TITLE
Maths in gitbook format no longer rendering as of yesterday...

### ISSUE THREAD

**Issue by JeffreyRacine** [rstudio/bookdown#482] opened 2017-11-10 18:57 UTC
Greetings, 

I am using the latest versions of bookdown, markdown, and knitr. As of yesterday (?) the gitbook format is no longer rendering maths...

I tried the minimal book example, rendered that in gitbook format in RStudio, and pointed my browser at _book/index.html and the same thing happens so I doubt it is my project. Note that the equation on the first page of the minimal book example is not rendered properly, it appears as

```
 \(a^2 + b^2 = c^2\).
```

```
A Minimal Book Example
Yihui Xie
2017-11-10
Chapter 1 Prerequisites

This is a sample book written in Markdown. You can use anything that Pandoc’s Markdown supports, e.g., a math equation \(a^2 + b^2 = c^2\).

For now, you have to install the development versions of bookdown from Github:

devtools::install_github("rstudio/bookdown")

Remember each Rmd file contains one and only one chapter, and a chapter is defined by the first-level heading #.

To compile this example to PDF, you need to install XeLaTeX.
```

System info follows. Thanks!

```
> devtools::session_info('bookdown')
Session info --------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, darwin17.0.0        
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  en_CA.UTF-8                 
 tz       <NA>                        
 date     2017-11-10                  

Packages ------------------------------------------------------------------------------------------------------
 package   * version date       source                            
 backports   1.1.1   2017-09-25 CRAN (R 3.4.2)                    
 base64enc   0.1-3   2015-07-28 CRAN (R 3.4.0)                    
 bitops      1.0-6   2013-08-17 CRAN (R 3.4.0)                    
 bookdown    0.5.6   2017-11-09 Github (rstudio/bookdown@d960243) 
 caTools     1.17.1  2014-09-10 CRAN (R 3.4.0)                    
 digest      0.6.12  2017-01-27 CRAN (R 3.4.0)                    
 evaluate    0.10.1  2017-06-24 CRAN (R 3.4.0)                    
 graphics  * 3.4.2   2017-10-08 local                             
 grDevices * 3.4.2   2017-10-08 local                             
 highr       0.6     2016-05-09 CRAN (R 3.4.0)                    
 htmltools   0.3.6   2017-04-28 CRAN (R 3.4.0)                    
 jsonlite    1.5     2017-06-01 CRAN (R 3.4.0)                    
 knitr       1.17.9  2017-10-26 Github (yihui/knitr@6f69c42)      
 magrittr    1.5     2014-11-22 CRAN (R 3.4.0)                    
 markdown    0.8     2017-04-20 CRAN (R 3.4.1)                    
 methods   * 3.4.2   2017-10-08 local                             
 mime        0.5     2016-07-07 CRAN (R 3.4.0)                    
 Rcpp        0.12.13 2017-09-28 CRAN (R 3.4.2)                    
 rmarkdown   1.7.3   2017-11-10 Github (rstudio/rmarkdown@63a37ae)
 rprojroot   1.2     2017-01-16 CRAN (R 3.4.0)                    
 stats     * 3.4.2   2017-10-08 local                             
 stringi     1.1.5   2017-04-07 CRAN (R 3.4.0)                    
 stringr     1.2.0   2017-02-18 CRAN (R 3.4.0)                    
 tools       3.4.2   2017-10-08 local                             
 utils     * 3.4.2   2017-10-08 local                             
 yaml        2.1.14  2016-11-12 CRAN (R 3.4.0)                    
> rmarkdown::pandoc_version()
[1] ‘1.19.2.1’
> system('pdflatex --version')
pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017/MacPorts 2017_2)
kpathsea version 6.2.3
Copyright 2017 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.32; using libpng 1.6.34
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with poppler version 0.57.0
```

**Comment by yihui** [comment] 2017-11-10 19:12
Should be fixed now. Thanks for the report!

**Closed** 2017-11-10 19:12 UTC

**Comment by RLesur** [comment] 2019-10-30 02:00
@kimberly-bastille I cannot reproduce the issue. Could you provide more information, please?
