### ISSUE TITLE
example environment does not work on its own

### ISSUE THREAD

**Issue by dietrichson** [rstudio/bookdown#359] opened 2017-03-08 14:16 UTC
Debug1.Rmd

This throws an error "! LaTeX Error: Environment example undefined."

However is I add a theorem like in debug2.Rmd it compiles without issue.
[debug.zip](https://github.com/rstudio/bookdown/files/827888/debug.zip)

**Comment by yihui** [comment] 2017-03-10 03:59
Duplicate of #291. Please

```r
devtools::install_github('rstudio/bookdown')
```

**Closed by yihui** 2017-03-10 03:59 UTC
