### ISSUE TITLE
Incorrect labelling of example, theorem etc. when split by section for gitbook output

### ISSUE THREAD

**Issue by dataopt** [rstudio/bookdown#522] opened 2018-01-27 15:00 UTC
For the following minimal example rendered using the latest github version of bookdown,
````
---
title: "A Book"
author: "Frida Gomam"
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    split_by: section
documentclass: book
---

# First chapter

```{example}
First example.
```

# Second chapter

## Subsection

```{example}
Subsection example.
```

```{theorem}
This is a theorem.
```
````

The example and the theorem in the second chapter receive incorrect labels.  They are labelled as Example 1.2 and Theorem 1.1.  They should be Example 2.1 and Theorem 2.1 instead.  (See image.)
<img width="582" alt="screen shot 2018-01-27 at 9 57 20 am" src="https://user-images.githubusercontent.com/28999218/35473081-8a0f8268-0348-11e8-981d-f99e9233895e.png">

**Comment by yihui** [comment] 2018-01-29 04:15
Sounds like a bug, but I don't have time until perhaps a few weeks later. If you can figure out a fix, a pull request is welcome as usual! :)

**Comment by cderv** [comment] 2021-03-18 17:37
It seems to be fixed now. I can't reproduce the bug with the example above. 

If there is still issue with that, please open a new issue with a reproducible example.

**Closed by cderv** 2021-03-18 17:37 UTC
Labels: bug
