### ISSUE TITLE
Names in environments throwing superfluous code in PDF output...

### ISSUE THREAD

**Issue by JeffreyRacine** [rstudio/bookdown#300] opened 2017-01-14 16:54 UTC
Greetings,

First, thanks for fixing the example environment (#291). I want to use the naming and referencing features. In HTML they are working perfectly, but PDF is another story... the following minimal example replicates (hopefully)... 

    ---
    output: bookdown::pdf_book
    ---
    
    ```{example,name="Stationary",label="staexa"}
    Check
    ```
    
    Example \@ref(ex:staexa)
    
    In PDF this throws
    
    ```Contents
    Example 0.1 (Stationary). <div class="example"><span class="example" id="ex:staexa"><strong> </strong></span>Check
    Example 0.1
    ```

So referencing is working but getting the unwanted HTML stuff when naming the example... seems to apply to all environments for what that is worth (theorem etc.)

Thanks!

**Comment by yihui** [comment] 2017-01-19 03:36
I cannot reproduce it. My output:

![image](https://cloud.githubusercontent.com/assets/163582/22092748/ea30af7c-ddc5-11e6-809b-1bfde29da91c.png)

I guess you might be using a Pandoc version that is not 1.17.2. Please report the following info:

```r
devtools::session_info('bookdown')
rmarkdown::pandoc_version()
```

**Comment by JeffreyRacine** [comment] 2017-01-19 12:08
Thanks. 

 
Using latest pandoc (1.19.1)
 
> devtools::session_info('bookdown')
rmarkdown::pandoc_version()
Session info -------------------------------------------------------------------
setting  value
version  R version 3.3.2 (2016-10-31)
system   x86_64, darwin16.1.0
ui       X11
language (EN)
collate  en_CA.UTF-8
tz       America/Toronto
date     2017-01-19
 
Packages -----------------------------------------------------------------------
package   * version date       source
backports   1.0.5   2017-01-18 CRAN (R 3.3.2)
base64enc   0.1-3   2015-07-28 CRAN (R 3.3.0)
bitops      1.0-6   2013-08-17 CRAN (R 3.3.0)
bookdown    0.3.7   2017-01-13 Github (rstudio/bookdown@2211cd0)
caTools     1.17.1  2014-09-10 CRAN (R 3.3.0)
digest      0.6.11  2017-01-03 CRAN (R 3.3.2)
evaluate    0.10    2016-10-11 CRAN (R 3.3.1)
highr       0.6     2016-05-09 CRAN (R 3.3.0)
htmltools   0.3.5   2016-03-21 CRAN (R 3.3.0)
jsonlite    1.2     2016-12-31 CRAN (R 3.3.2)
knitr       1.15.6  2017-01-08 Github (yihui/knitr@f936809)
magrittr    1.5     2014-11-22 CRAN (R 3.3.0)
markdown    0.7.10  2016-12-16 Github (rstudio/markdown@1e1b061)
mime        0.5     2016-07-07 CRAN (R 3.3.1)
Rcpp        0.12.9  2017-01-14 CRAN (R 3.3.2)
rmarkdown   1.3     2016-12-21 CRAN (R 3.3.2)
rprojroot   1.2     2017-01-16 CRAN (R 3.3.2)
stringi     1.1.2   2016-10-01 CRAN (R 3.3.1)
stringr     1.1.0   2016-08-19 CRAN (R 3.3.1)
yaml        2.1.14  2016-11-12 CRAN (R 3.3.2)
> rmarkdown::pandoc_version()
[1] ‘1.19.1’
> 
 

From: 
Yihui Xie <notifications@github.com>
Reply-To: rstudio/bookdown <reply@reply.github.com>
Date: Wednesday, January 18, 2017 at 22:36
To: rstudio/bookdown <bookdown@noreply.github.com>
Cc: "Racine, Jeffrey" <racinej@mcmaster.ca>, Author <author@noreply.github.com>
Subject: Re: [rstudio/bookdown] Names in environments throwing superfluous code in PDF output... (#300)


 

devtools::session_info('bookdown')
rmarkdown::pandoc_version()

**Comment by yihui** [comment] 2017-01-19 21:33
It turns out 1.19.1 is indeed the problem. Bookdown was only tested against 1.17.2, which is the version of Pandoc bundled in the RStudio IDE. Higher versions have not been tested yet.

**Comment by yihui** [comment] 2017-01-19 22:14
I think I figured out the change in Pandoc 1.19, but I don't know if it will be fixed or not: https://github.com/jgm/pandoc/issues/3368

**Closed** 2017-03-25 06:32 UTC
Labels: bug

**Comment by yihui** [comment] 2017-03-25 06:33
Pandoc 1.19.x should work with the development version of bookdown now:

```r
devtools::install_github('rstudio/bookdown')
```

**Comment by JeffreyRacine** [comment] 2017-03-25 11:19
Many thanks!
