### ISSUE TITLE
Perl warning message when build gitbook

### ISSUE THREAD

**Issue by junchenfeng** [rstudio/bookdown#169] opened 2016-08-02 16:37 UTC
I received the following warning msg

> Warning messages:
1: running command '"C:\PROGRA~2\MIKTEX~1.9\miktex\bin\latexmk.exe" -v' had status 1 
2: The LaTeX package latexmk was not correctly installed. 
3: running command '"C:\PROGRA~2\MIKTEX~1.9\miktex\bin\latexmk.exe" -v' had status 1 
4: In FUN(...) :
  Perl must be installed and put on PATH for latexmk to work

I have installed the lastest activeState perl and reinstalled latexmk. I still get the warning message.

The consequence appears to be no pdf available for download.

**Comment by kevinushey** [comment] 2016-08-02 16:51
Is `perl` on the PATH? What does `Sys.which("perl")` return?

**Comment by junchenfeng** [comment] 2016-08-02 18:45
Perl is on the path. `Sys.which("perl")` return 

> "C:\\Perl64\\bin\\perl.exe"

I verified that it is the latest perl.

**Comment by kevinushey** [comment] 2016-08-02 19:05
Interestingly, I see an error when I attempt to run `latexmk.exe` from within RStudio:

```
> system("\"C:\\PROGRA~2\\MIKTEX~1.9\\miktex\\bin\\latexmk.exe\" -v")
latexmk.exe: MiKTeX encountered an internal error.
Warning: running command '"C:\PROGRA~2\MIKTEX~1.9\miktex\bin\latexmk.exe" -v' had status 1
```

Yet it works fine from the command line (`cmd.exe`):

```
C:\Program Files (x86)\MiKTeX 2.9\miktex\bin>latexmk.exe -v

Latexmk, John Collins, 22 April 2016. Version 4.45
```

This sounds like a duplicate of https://github.com/rstudio/bookdown-demo/issues/3. It looks like `latexmk.exe` is really fussy about how it is executed on Windows:

1. `latexmk.exe` must be on the `PATH`;
2. `perl.exe` must be on the `PATH`;
3. `latexmk.exe` _must_ be executed through `shell`, and the path should not be specified directly.

In sum, for `latexmk.exe` to be executed through R on Windows, it looks like we need to call it as:

    shell("latexmk.exe -v")

cc: @yihui; is this resolved now, or do we need changes in `rmarkdown` to accommodate this?

**Comment by yihui** [comment] 2016-08-05 22:10
@kevinushey It is weird that the `shell()` trick is only required for certain Windows platforms (I don't know which).

This warning can be safely ignored. I'll send a PR to rmarkdown to suppress the warning, since it is very confusing.

**Closed** 2016-08-05 22:22 UTC

**Comment by yihui** [comment] 2016-08-05 22:24
This should get rid of the warning:

```r
devtools::install_github('rstudio/rmarkdown')
```
