### ISSUE TITLE
Can't cross-reference when knitting to Word

### ISSUE THREAD

**Issue by MCM-Math** [rstudio/bookdown#650] opened 2018-11-16 14:02 UTC
I'm not sure how to properly place references that would be in a Word document. I tried putting it in square brackets, but that seems to reference file locations, not numbers for sections, figures, etc.

**Comment by yihui** [comment] 2019-05-10 16:10
Duplicate of https://github.com/yihui/knitr/issues/1636

**Closed by yihui** 2019-05-10 16:10 UTC
