### ISSUE TITLE
Chunk name added to plot caption

### ISSUE THREAD

**Issue by antaldaniel** [rstudio/bookdown#336] opened 2017-02-10 23:08 UTC
I guess that this may be a question, not an issue, but after many searches I cannot find an example. 

In the book examples, 

> {r foo, fig.cap = "My caption", echo=F, message=F, warning=F }
> some code plot (...) }

Should result in a caption below the plot (depending on the chapter numbering)
> Figure 1.1 My caption

However, I get 
>Figure 1.1 (#foo) My caption 

instead. How can I avoid adding the chunk name in parenthesis with a # to be added to the caption? (It shows up both in html and pdf)

**Comment by yihui** [comment] 2017-03-08 05:54
Could you provide a minimal, self-contained, and reproducible example? Please also tell me how you actually rendered the book, and include your session info:

```r
devtools::session_info('bookdown')
```

**Comment by kylebarron** [comment] 2017-03-18 05:20
I have the same issue. From making the reproducible example, it seems as if it has to do with the number of characters used for the code chunk label. In the code: (the two backslashes added only to keep Github from formatting the code chunks)

```
---
title: "Untitled"
output:
  bookdown::pdf_document2:
    fig_caption: true
---
```{r pressure, fig.cap = "test"}
plot(pressure) 
\```
```{r pressure_test, fig.cap = "test"}
plot(pressure) 
\```
```
The first has the correct caption, while the second has the caption "Figure 2: (#fig:pressure_test)test".
[test.pdf](https://github.com/rstudio/bookdown/files/852182/test.pdf)

My session info is as follows:
> devtools::session_info("bookdown")
Session info ----------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       <NA>                        
 date     2017-03-17                  

Packages --------------------------------------------------------------------------------------------------------------------------------------
 package   * version date       source        
 backports   1.0.5   2017-01-18 CRAN (R 3.3.2)
 base64enc   0.1-3   2015-07-28 CRAN (R 3.3.2)
 bitops      1.0-6   2013-08-17 CRAN (R 3.3.2)
 bookdown    0.3     2016-11-28 CRAN (R 3.3.2)
 caTools     1.17.1  2014-09-10 CRAN (R 3.3.2)
 digest      0.6.12  2017-01-27 CRAN (R 3.3.2)
 evaluate    0.10    2016-10-11 CRAN (R 3.3.2)
 highr       0.6     2016-05-09 CRAN (R 3.3.2)
 htmltools   0.3.5   2016-03-21 CRAN (R 3.3.2)
 jsonlite    1.3     2017-02-28 CRAN (R 3.3.2)
 knitr       1.15.1  2016-11-22 CRAN (R 3.3.2)
 magrittr  * 1.5     2014-11-22 CRAN (R 3.3.2)
 markdown    0.7.7   2015-04-22 CRAN (R 3.3.2)
 mime        0.5     2016-07-07 CRAN (R 3.3.2)
 Rcpp        0.12.9  2017-01-14 CRAN (R 3.3.2)
 rmarkdown   1.3     2016-12-21 CRAN (R 3.3.2)
 rprojroot   1.2     2017-01-16 CRAN (R 3.3.2)
 stringi     1.1.2   2016-10-01 CRAN (R 3.3.2)
 stringr   * 1.2.0   2017-02-18 CRAN (R 3.3.2)
 yaml        2.1.14  2016-11-12 CRAN (R 3.3.2)

**Comment by yihui** [comment] 2017-03-18 05:59
@kylebarron Underscores are not allowed in chunk labels: https://bookdown.org/yihui/bookdown/figures.html

**Comment by mbojan** [comment] 2017-03-20 11:36
Just tripped on the `_` myself... Can this limitation be overcomed, or is it something that probably will never be fixed?

**Comment by yihui** [comment] 2017-03-20 16:10
@mbojan It is by design. The underscore is a special character in LaTeX, which can [make my life more complicated](https://xkcd.com/1638/) if I want to support it.

**Comment by mbojan** [comment] 2017-03-20 16:18
Ok. Although it ruins my elaborated chunk-naming scheme... ;)

**Comment by yihui** [comment] 2017-03-20 20:53
Hi @antaldaniel, if you are able to provide a reproducible example, I can take a look at it, otherwise I'm going to close this issue. Thanks!

**Comment by kylebarron** [comment] 2017-03-20 22:37
I missed that paragraph in the bookdown figures reference; apologies. So for clarification, we can't use spaces either?

**Comment by yihui** [comment] 2017-03-20 22:47
@kylebarron You cannot use spaces in chunk labels, either. That is because the space is a special character in HTML paths (it is often encoded in `%20`). Similarly, I just want to make my own life easier by requiring absolutely "safe" characters in chunk labels instead of worrying about encoding/decoding certain characters all the time. It is an absolutely selfish reason to save myself time so I can get more important things done.

**Comment by antaldaniel** [comment] 2017-03-21 11:00
Unfortunately I am in a rainforest with almost no internet access, so I cannot do it now. If you keep it open, I will do it about 10 days from now. Sorry.

**Comment by yihui** [comment] 2017-03-21 16:18
@antaldaniel No worries at all! Thanks!

**Closed** 2017-05-17 03:15 UTC

**Comment by pinusm** [comment] 2017-05-28 14:29
I see this happens when my chunk options include a special unescaped character, such as '\'.
`
```{r poweranalysis, include="TRUE", fig.cap= "A-priori sample size required for comparing correlations, plotted by effect-size and Beta. \n Note: The sample size in the figure is the combined sample size, for a two independent correlations test, N = n1 + n2. This also assumes equal group sizes, n1 = n2. Plotted using G-Power 3.1. The required sample size in the present study is double that shown here, as there are two two-independent correlations tests."}
knitr::include_graphics("figures/plan/poweranalysis.png")
```
`
but not when I removed the '\n'.
( I'm trying to insert a new line in the caption. This didn't work, but I did stumble upon the chunk-name-caption thingy.)

**Comment by kenneth-meehan** [comment] 2018-03-23 18:45
So we have to remove any spaces in any chunk names now?

**Comment by antaldaniel** [comment] 2018-03-24 09:40
I think if you use Windows, you should remove all spaces, hyphens and underscores, and for included files, such as include_graphic files, keep the path very short, preferably simple relative path like images/   .  I had latex errors from -, from space, from _ and from long path, too.

**Comment by kenneth-meehan** [comment] 2018-03-25 14:19
I also had to remove ampersands from chunk labels.
