### ISSUE TITLE
Fig caption position in pdf (from Bookdown).

### ISSUE THREAD

**Issue by jcalonsoc** [rstudio/bookdown#1282] opened 2021-11-02 23:53 UTC
I am trying to render a book using bookdown in HTML, pdf, and epub format. I am rendering an image from a chunk (in r) with fig.topcaption=TRUE. In the HTML and pub  file every thing works fine, but in the pdf format the caption is below the figure. 
Is there any way to solve this problem?

````
--- 
title: "A Minimal Book Example"
author: "Yihui Xie"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book

---

# Intro


```{r F1, echo=FALSE, out.width='70%', fig.align='left', fig.cap='Example.',fig.topcaption=TRUE}
library(ggplot2)
ggplot(mpg, aes(displ, hwy, colour = class)) + 
  geom_point()
```

````

My section info is

R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS  11.4, RStudio 1.4.1655

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3 bookdown_0.24.3 digest_0.6.28  
  evaluate_0.14   fastmap_1.1.0   glue_1.4.2     
  graphics_4.0.3  grDevices_4.0.3 highr_0.9      
  htmltools_0.5.2 jquerylib_0.1.4 jsonlite_1.7.2 
  knitr_1.36      magrittr_2.0.1  methods_4.0.3  
  rlang_0.4.12    rmarkdown_2.11  stats_4.0.3    
  stringi_1.7.5   stringr_1.4.0   tinytex_0.34   
  tools_4.0.3     utils_4.0.3     xfun_0.27      
  yaml_2.2.1

**Comment by cderv** [comment] 2021-11-03 10:26
Hi @jcalonsoc , 

Thanks for the question. 

`fig.topcaption` is only working with HTML-like output. It is not working with PDF. This is not supported by **knitr** yet so the behavior you see is unfortunately  expected in **bookdown**. This is already discussed in #866

You can add a 👍 in the **knitr** issue  https://github.com/yihui/knitr/issues/1990  tracking this. We will probably tackle it in the future.

I'll close the issue here as we track that already on **bookdown** and mainly **knitr**

**Comment by cderv** [comment] 2021-11-03 10:26
Duplicate of #866

**Closed by cderv** 2021-11-03 10:26 UTC
