### ISSUE TITLE
[FR] boolean to turn off collapsed navbar in bs4_book

### ISSUE THREAD

**Issue by Pindar777** [rstudio/bookdown#1250] opened 2021-09-02 17:24 UTC
When scrolling inside a chapter of a bs4_book the navbar on the right side changes (via javascript) between navbar and navbar active.

If there are three headlines present this navbar TOC  opens up and shows the third hierarchy.
**I would like to turn  this (nice) feature off with a boolean.**
This feature is crucial for my project, since javascript is disabled on the server that hosts my bs4_book and the h3-topics shall be "printed". I could implement a change inside my fork for now...

However, up until now I did not find the correct place inside the code how to do this. I was searching inside `bs4_book.R`. 

I did manage to always show `head` or activate the TOC on the left side. I guess it could be done by manipulating `# Within chapter nav`.

**Comment by cderv** [comment] 2021-09-02 17:33
Hi, 

Can you provide an example / illustration of what you are looking for ? I am not sure to clearly see the intended result.

Also, `bs4_book()` is powered by Bootstrap, which requires JQuery I believe. So it is possible that other feature cannot be working well. 

Thank you.

**Comment by Pindar777** [comment] 2021-09-02 18:18
Hi @cderv,

Thank you for your fast reaction.
I try to make the goal clear with a verbal example:

# H1 Chapter 1
## H2 Top1
### H3 001
### H3 002
## H2 Top 2

Let's assume there are **long texts** between the headlines of this chapter. After knitting the book opens. You click oh CHAPTER 1 and on the right side ONLY shows the H2s (since there is a long introduction above ## H2 Top1). However, if you are scrolling down reaching the text of ## H2 and/or ### H3 001 the navbar on the right side suddenly shows all H3s. It is hence not collapsed anymore. 

Actually we do not need to care about the JavaScript but just change the default TOC depth shown of the right navbar to always show all H2 and H3 inside the automatically generated space. If it's too long, there gonna be a scrollbar inside the navbar automatically.

At the moment I don't have a proper screen shot at hand. But I hope I made the goal clear.

**Comment by Pindar777** [comment] 2021-09-02 18:27
@cderv 

It should be as with the current ggplot2 book as desktop page 
![Uploading Screenshot_20210902-202622.png…]()

**Comment by Pindar777** [comment] 2021-09-02 18:33
I'm using the newest bookdown with R 4.1.1 on windows 10

**Comment by Pindar777** [comment] 2021-09-03 07:49
@cderv Please have a look at these screenshots:
![Bookdown_bs4_book_navbar_collapsed_by_default](https://user-images.githubusercontent.com/44449736/131967425-f42ebf8a-a02b-4fac-bf2a-254c1f432ceb.jpg)
![Bookdown_bs4_book_navbar_uncollapsed_for_active_region_through_scrolling](https://user-images.githubusercontent.com/44449736/131967433-34e1d504-ccf1-4515-aa86-34907d7e710c.jpg)

```
sessionInfo()
## R version 4.1.1 (2021-08-10)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 19043)
## 
## Matrix products: default
## 
## locale:
## [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
## [3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
## [5] LC_TIME=German_Germany.1252    
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
##  [1] glue_1.4.2           ftExtra_0.2.0        openxlsx_4.2.4      
##  [4] flextable_0.6.7      rvg_0.2.5            cowplot_1.1.1       
##  [7] officer_0.3.19       officedown_0.2.3.002 knitr_1.33          
## [10] gt_0.3.1             forcats_0.5.1        stringr_1.4.0       
## [13] dplyr_1.0.7          purrr_0.3.4          readr_2.0.1         
## [16] tidyr_1.1.3          tibble_3.1.4         ggplot2_3.3.5       
## [19] tidyverse_1.3.1     
## 
## loaded via a namespace (and not attached):
##  [1] httr_1.4.2        sass_0.4.0        jsonlite_1.7.2    modelr_0.1.8     
##  [5] bslib_0.2.5.1     assertthat_0.2.1  cellranger_1.1.0  yaml_2.2.1       
##  [9] gdtools_0.2.3     pillar_1.6.2      backports_1.2.1   uuid_0.1-4       
## [13] digest_0.6.27     rvest_1.0.1       colorspace_2.0-2  htmltools_0.5.2  
## [17] pkgconfig_2.0.3   broom_0.7.9       haven_2.4.3       bookdown_0.24.1  
## [21] scales_1.1.1      tzdb_0.1.2        downlit_0.2.1     generics_0.1.0   
## [25] ellipsis_0.3.2    cachem_1.0.6      withr_2.4.2       cli_3.0.1        
## [29] magrittr_2.0.1    crayon_1.4.1      readxl_1.3.1      memoise_2.0.0    
## [33] evaluate_0.14     fs_1.5.0          fansi_0.5.0       xml2_1.3.2       
## [37] tools_4.1.1       data.table_1.14.0 hms_1.1.0         lifecycle_1.0.0  
## [41] munsell_0.5.0     reprex_2.0.1      zip_2.2.0         compiler_4.1.1   
## [45] jquerylib_0.1.4   systemfonts_1.0.2 rlang_0.4.11      grid_4.1.1       
## [49] rstudioapi_0.13   base64enc_0.1-3   rmarkdown_2.10    gtable_0.3.0     
## [53] DBI_1.1.1         R6_2.5.1          lubridate_1.7.10  fastmap_1.1.0    
## [57] utf8_1.2.2        stringi_1.7.4     Rcpp_1.0.7        vctrs_0.3.8      
## [61] dbplyr_2.1.1      tidyselect_1.1.1  xfun_0.25

```

**Comment by cderv** [comment] 2021-09-03 08:18
Unfortunately, I think I can't reproduce this behavior. 

Minimal reprex: 
````r
# new book project dir
dir.create(tmp_dir <- tempfile())
# Load book
library(bookdown)
# Create template book
book <- create_bs4_book(tmp_dir)
# Render book
res <- render_book(book)
# Serve the book
servr::httd(dirname(res))
````

This will open a preview of the book. 

Go to chapter 2 and look at the toc on the right. All header levels are uncollapsed. 

I also tweaked this project more to create a long page. You can open the project folder in `book` folder (on Windows runs `shell.exec(book)` if you want to open the folder)

I did this
```r
file <- file.path(book, "02-cross-refs.Rmd")
content <- c("## Another sub header", "Some text", "### A sub sub header")
xfun::write_utf8(c(xfun::read_utf8(file), "", content), file)
res <- render_book(book)
servr::httd(dirname(res))
```

You can now open Chapter 3: I see all the level uncollapsed
![image](https://user-images.githubusercontent.com/6791940/131973918-2a799d2e-6b91-4e48-a23e-3d89998710bb.png)


Can you reproduce using these code steps ? 

Do you see the same behavior in different browsers ?

**Comment by Pindar777** [comment] 2021-09-03 10:56
@cderv Thank you for the code to generate a reprex.
Well, the ###H3s are collapsed by default
![image](https://user-images.githubusercontent.com/44449736/131994602-5903805c-54f7-4e9d-9809-54f790a17eb3.png)

vs with scrolling

![image](https://user-images.githubusercontent.com/44449736/131994809-fd14d51f-6ac9-4de2-a365-2b2c847c673b.png)

**Comment by Pindar777** [comment] 2021-09-03 12:32
@cderv Update:
I can reproduce the "standard" behaviour with my old R 4.1.0 environment
![image](https://user-images.githubusercontent.com/44449736/132005613-8c879052-9b83-49c9-8a6b-c5fec3400f7b.png)

**Comment by Pindar777** [comment] 2021-09-03 12:49
Hence, the source of the different knitting-behaviour is not bookdown...

**Comment by cderv** [comment] 2021-09-03 14:16
Thanks. 

My example was not perfect I forgot a new line. Second part should be like this in the full example

````r
# new book project dir
dir.create(tmp_dir <- tempfile())
# Load book
library(bookdown)
# Create template book
book <- create_bs4_book(tmp_dir)
# Render book
res <- render_book(book)
# Serve the book
servr::httd(dirname(res))

# Add content for a level 3 header
file <- file.path(book, "02-cross-refs.Rmd")
content <- c("## Another sub header", "Some text", "", "### A sub sub header")
xfun::write_utf8(c(xfun::read_utf8(file), "", content), file)
res <- render_book(book)
servr::httd(dirname(res))
````

Otherwise the level 3 header is not added. 

I have update to R 4.1.1 and still can't reproduce. 
![image](https://user-images.githubusercontent.com/6791940/132018468-0f595b59-82b0-4f75-95c8-c267f84b10ef.png)

<details closed>
<summary> <span title='Click to Expand'> Session Info </span> </summary>

```r

- Session info -------------------------------------------------------------------------
 setting  value                       
 version  R version 4.1.1 (2021-08-10)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  French_France.1252          
 ctype    French_France.1252          
 tz       Europe/Paris                
 date     2021-09-03                  

- Packages -----------------------------------------------------------------------------
 package   * version date       lib source                            
 base64enc   0.1-3   2015-07-28 [1] standard (@0.1-3)                 
 bookdown  * 0.24.1  2021-09-03 [1] Github (rstudio/bookdown@2eabc9a) 
 digest      0.6.27  2020-10-24 [1] standard (@0.6.27)                
 evaluate    0.14    2019-05-28 [1] standard (@0.14)                  
 fastmap     1.1.0   2021-01-25 [1] standard (@1.1.0)                 
 glue        1.4.2   2020-08-27 [1] standard (@1.4.2)                 
 highr       0.9     2021-04-16 [1] standard (@0.9)                   
 htmltools   0.5.2   2021-08-25 [1] standard (@0.5.2)                 
 jquerylib   0.1.4   2021-04-26 [1] standard (@0.1.4)                 
 jsonlite    1.7.2   2020-12-09 [1] standard (@1.7.2)                 
 knitr       1.33.9  2021-09-01 [1] Github (yihui/knitr@0dcd462)      
 magrittr    2.0.1   2020-11-17 [1] standard (@2.0.1)                 
 rlang       0.4.11  2021-04-30 [1] standard (@0.4.11)                
 rmarkdown   2.10.6  2021-09-03 [1] Github (rstudio/rmarkdown@eaf6efc)
 stringi     1.7.3   2021-07-16 [1] standard (@1.7.3)                 
 stringr     1.4.0   2019-02-10 [1] standard (@1.4.0)                 
 tinytex     0.33    2021-08-05 [1] standard (@0.33)                  
 xfun        0.25    2021-08-06 [1] standard (@0.25)                  
 yaml        2.2.1   2020-02-01 [1] standard (@2.2.1)                 

[1] C:/Users/chris/Documents/R/win-library/4.1
[2] C:/Program Files/R/R-4.1.1/library

```

</details>
<br>

I don't really know what could cause this issue unless some browser specificity or version differences in package.

**Comment by Pindar777** [comment] 2021-09-03 16:54
@cderv I can access the website after executing `servr::httd(dirname(res))` inside of Visual Studio Code.
I guess that es something like a privat session. And the result is the same.

So I guess there are version differences in package(s). I'm gonna dwell on it (and post a pull request for bookdown on another connected issue in terms of footnotes).

Cheers

**Comment by Pindar777** [comment] 2021-09-06 13:30
@cderv I pinned it down to the lib `bootstrap-4.60`!
I have two different versions of the same lib (with the same name) and the important difference is this css-code at the end of the desired working file:

```
@media (min-width: 576px){.nav{display:flex !important;display:-webkit-flex !important}.nav:not(.nav-stacked):not(.flex-column){float:none !important}.nav:not(.nav-stacked):not(.flex-column)>.bslib-nav-spacer{margin-left:auto !important}.nav:not(.nav-stacked):not(.flex-column)>.form-inline{margin-top:auto;margin-bottom:auto}.nav.nav-stacked{flex-direction:column;-webkit-flex-direction:column;height:100%}.nav.nav-stacked>.bslib-nav-spacer{margin-top:auto !important}}
```

**Comment by cderv** [comment] 2021-09-06 13:55
@Pindar777 are you able to know from which files these line are ? 
I can't find this. 
````css
/* do not allow collapsed navbar in bs4_book */
````

The bootstrap version used is tied to the **bslib** package version. can you confirm the version you are using ? 
It seems like **bslib** 0.3.0 is now on CRAN

**Comment by Pindar777** [comment] 2021-09-06 14:49
@cderv I have been using `bslib_0.2.5.1` and copied (and formatted) the needed css inside my personal css where I added the cited headline. 

Now I can confirm that `bslib 0.3.0` is on cran an the `bootstrap-4.60` does contain the needed css.
Hence, the issue is solved :-)

**Comment by cderv** [comment] 2021-09-06 15:22
Ok so it was a **bslib** version issue, with some custom css of yours in the middle. Glad with solve this! 

I'll close this then. 

Thanks.

**Closed by cderv** 2021-09-06 15:22 UTC

**Comment by cderv** [comment] 2021-10-12 18:05
> but I have the opposite request - is there any easy way to turn the old behavior back on (going back to the collapsed H3s) without rolling back to an older version of bslib?

Hi, Can you open a new issue and share an example so that I can try on my end ? I don't really know what the "old behavior" is and it would help be on the same page. 

Thank you !
