### ISSUE TITLE
Java script bug?

### ISSUE THREAD

**Issue by nikolaussucher** [rstudio/bookdown#584] opened 2018-05-27 04:55 UTC
Hi, I noticed a weird bug: on my iPhone and MacBook Pro (using any browser) I see the toolbar with the icons for the toc, search, edit and download. On my iPad it doesn’t show (again any browser). When I touch the area where it should be and move my finger up, the icons appear but disappear when I let go. If I touch the blank screen, where the icons should be, I get the expected response.

**Comment by dataopt** [comment] 2018-05-27 08:54
This is a known issue.  The root problem is in the gitbook template.  See #60.

**Comment by yihui** [comment] 2018-05-27 15:26
Duplicate of #60

**Closed by yihui** 2018-05-27 15:26 UTC
