### ISSUE TITLE
Chinese comments are not supported in bs4_book？

### ISSUE THREAD

**Issue by perlatex** [rstudio/bookdown#1260] opened 2021-09-27 11:50 UTC
I have posted the same issue https://community.rstudio.com/t/chinese-comments-are-not-supported-in-bs4-book/114837

According to <https://bookdown.org/yihui/bookdown/html.html#bs4-book>,
I use the RStudio (*File > New Project > New Directory > Book project using bookdown*) and select `bs4_book`,  then write a new `bs4_book`: 

i add a R code with english comments

````markdown
```{r}
#  Sequence
1:5
```
````

try this
```r
bookdown::render_book("index.Rmd")
```

it work correctly.

**However**, when  i add a R code with chinese comments
````markdown
```{r}
#  序列
1:5
```
````

I got this error.
```r
Error in gsub("<U+2029>", "\033", text[is_comment], fixed = TRUE)
```

```r
> xfun::session_info('bookdown')
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042), RStudio 2021.9.0.341

Locale:
  LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
  LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
  LC_TIME=Chinese (Simplified)_China.936    

Package version:
  base64enc_0.1.3 bookdown_0.24   digest_0.6.27   evaluate_0.14   fastmap_1.1.0  
  glue_1.4.2      graphics_4.0.5  grDevices_4.0.5 highr_0.9       htmltools_0.5.2
  jquerylib_0.1.4 jsonlite_1.7.2  knitr_1.34      magrittr_2.0.1  methods_4.0.5  
  rlang_0.4.11    rmarkdown_2.11  stats_4.0.5     stringi_1.7.4   stringr_1.4.0  
  tinytex_0.33    tools_4.0.5     utils_4.0.5     xfun_0.26       yaml_2.2.1     
```

```r
> sessioninfo::platform_info()
 setting  value                         
 version  R version 4.0.5 (2021-03-31)  
 os       Windows 10 x64                
 system   x86_64, mingw32               
 ui       RStudio                       
 language (EN)                          
 collate  Chinese (Simplified)_China.936
 ctype    Chinese (Simplified)_China.936
 tz       Asia/Taipei                   
 date     2021-09-27              
```

**Comment by cderv** [comment] 2021-09-27 12:57
Hi, 

I believe this is an issue with **downlit** package used by `bs4_book()` format. The error comes from 
https://github.com/r-lib/downlit/blob/d559cf7dff5a3a8fc2406d6be72b12f68cc1c60c/R/highlight.R#L321

Can you try to see if you can reproduce using 
```r
downlit::highlight("#  序列\n1:5")
```
or
```r
downlit::highlight("#  序列
1:5")
```

Maybe don't copy paste as encoding could be an issue. 

I can't reproduce myself but I am on Windows 10 with French Language. 

If this is from **downlit**, we'll open the issue there with a reprex.

**Comment by perlatex** [comment] 2021-09-28 00:39
```r
downlit::highlight("#  序列\n1:5")
Error in gsub("<U+2029>", "\033", text[is_comment], fixed = TRUE) : 
  input string 1 is invalid UTF-8
```


```r
downlit::highlight("#  序列
+ 1:5")
Error in gsub("<U+2029>", "\033", text[is_comment], fixed = TRUE) : 
  input string 1 is invalid UTF-8
```

**Comment by cderv** [comment] 2021-09-28 08:02
Thanks @perlatex this means this is an issue in **downlit**. 

Can you open an issue there linking to this one and including the above reprex https://github.com/rstudio/bookdown/issues/1260#issuecomment-928518620 ? 

Repo is here: https://github.com/r-lib/downlit

I think the `gsub()` could require a `use_bytes = TRUE` or some better encoding handling.

Thank you !

**Comment by cderv** [comment] 2021-09-28 08:08
Looking at **downlit** to see if there was already an opened issue, it is possible that this opened PR https://github.com/r-lib/downlit/pull/112 would fix this.

@hadley I think this issue could be related.

**Comment by hadley** [comment] 2021-09-28 12:16
Yeah, I think that PR is related, although that fix is clearly not enough.

**Comment by cderv** [comment] 2021-09-29 10:13
@perlatex just to check, is your input Rmd file correctly encoded a UTF-8 ? 

I can reproduce with **downlit** (and I opened r-lib/downlit#113)

``` r
# String is latin-1 by default on my system
text <- "# é"
downlit::highlight(text)
#> Error in gsub("<U+2029>", "\033", text[is_comment], fixed = TRUE): input string 1 is invalid UTF-8

text_enc <- enc2utf8(text)
downlit::highlight(text_enc)
#> [1] "<span class='c'># é</span>"
```

But it does not fail within **bookdown** using `bs4_book()`. R Markdown ecosystem works in UTF-8 so content should be passed correctly to **downlit**. 

Does encoding the string to UTF-8 works also for you too with **downlit** ?

**Comment by cderv** [comment] 2021-09-29 16:25
@perlatex it is possible that r-lib/downlit#112 fix the issue. It does for my small reprex with **downlit**.

Can you try building your book after installing a version of downlit from the PR ? 

```r
remotes::install_github("r-lib/downlit#112")
```

You can reinstall CRAN version after your test using `install.packages()` or any other tool. 

Thank you!

**Comment by perlatex** [comment] 2021-10-02 14:23
Thank you very much @cderv.
This problem is solved through your method,
```r
remotes::install_github("r-lib/downlit")
```

**Comment by perlatex** [comment] 2021-10-02 14:25
```r
downlit::highlight("#  序列\n1:5")
[1] "<span class='c'>#  序列</span>\n<span class='m'>1</span><span class='o'>:</span><span class='m'>5</span>"
```

**Comment by cderv** [comment] 2021-10-04 08:15
Thanks ! 

I'll close this then but we'll update the minimum requirement of the **downlit** package in suggest of **bookdown** when next **downlit** release will be done. 

Thanks for the report.

**Closed by cderv** 2021-10-04 08:15 UTC
Labels: bug, bs4_book :hiking_boot:
