### ISSUE TITLE
LaTeX output: Unwanted space in text due to moving of floats

### ISSUE THREAD

**Issue by wuffi** [rstudio/bookdown#579] opened 2018-05-12 15:23 UTC
Whenever a float between two parts of text gets moved, an emtpy space is created in the text, because there is an empty line at the beginning and end of the figure environment in the LaTeX output.
Minimal example to reproduce the issue:
    
    ---
    output: pdf_document
    ---
    
    This is my first paragraph. 
    Next in the Rmd file would be the code for the figure.  
    The figure is correctly treated as a float by LaTeX, meaning that LaTeX will put it to the next suitable position.
    ```{r pressure, echo=FALSE, fig.cap="Example", out.width='0.5\\textwidth', fig.pos='B'}
      plot(pressure)
    ```
    The problem now is, that this leaves space to my second paragraph.
    Usually, this should not be the case.
    In pure LaTeX, there is a linebreak, of course, but no vertical space in addition.

**Comment by yihui** [comment] 2018-05-14 16:46
Duplicate of https://github.com/rstudio/rmarkdown/issues/1345

**Comment by yihui** [comment] 2018-05-14 16:47
In the future, when you [cross-post issues](https://yihui.name/en/2017/10/cross-posting/), please mention it. Thanks!

**Closed by yihui** 2018-05-14 16:47 UTC
