### ISSUE TITLE
PDF-Output: Using a pandoc template results in LaTeX-error `! Undefined control sequence.`

### ISSUE THREAD

**Issue by Woosah** [rstudio/bookdown#1340] opened 2022-05-23 07:46 UTC
- [x] [formatted your issue](https://yihui.org/issue/#please-format-your-issue-correctly) so it is easier for us to read?

- [x] included a minimal, self-contained, and reproducible example?

- [x] pasted the output from `xfun::session_info('bookdown')` in your issue?

- [x] upgraded all your packages to their latest versions (including your versions of R, the RStudio IDE, and relevant R packages)?

- [x] installed and tested your bug with the development version of the bookdown package using `remotes::install_github("rstudio/bookdown")` ?

------

I want to use a custom pandoc template for LaTeX output in bookdown. I am using the latest version of Rstudio and tinytex to build the book and I want to follow the procedure described [here](https://bookdown.org/yihui/rmarkdown-cookbook/latex-template.html), which had worked in the past without any problems. 

To reproduce the error, I open a new bookdown project and only add one line to `_output.yml` using the current `default.latex` template from pandoc without any changes from [here](https://github.com/jgm/pandoc-templates):

```
bookdown::pdf_book:
  includes:
    in_header: preamble.tex
  latex_engine: xelatex
  citation_package: natbib
  keep_tex: yes
  template: "default.latex"
```

This results in the following error:

```
output file: _main.knit.md

! Undefined control sequence.
l.246 {\centering \includegraphics
                                  [width=0.8\linewidth]{_main_files/figure-l... 

Error: LaTeX failed to compile _main.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See _main.log for more info.
Execution halted

Exited with status 1.
```

It seems that somehow the path for the figures produced in the code chunks is messed up during the second LaTeX run, leaving a PDF without any table of contents, cross-references or figures included.

This behavior is the same for me when I use a fully updated MikTeX-installation and not tinytex, too, But maybe I am missing something here...

### Session info:

```
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044), RStudio 2022.2.2.485

Locale: LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8    LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                    LC_TIME=German_Germany.utf8    

Package version:
  base64enc_0.1.3 bookdown_0.26.3 bslib_0.3.1     digest_0.6.29   evaluate_0.15   fastmap_1.1.0   fs_1.5.2        glue_1.6.2      graphics_4.2.0  grDevices_4.2.0
  highr_0.9       htmltools_0.5.2 jquerylib_0.1.4 jsonlite_1.8.0  knitr_1.39      magrittr_2.0.3  methods_4.2.0   R6_2.5.1        rappdirs_0.3.3  rlang_1.0.2    
  rmarkdown_2.14  sass_0.4.1      stats_4.2.0     stringi_1.7.6   stringr_1.4.0   tinytex_0.39    tools_4.2.0     utils_4.2.0     xfun_0.31       yaml_2.3.5
```

**Comment by cderv** [comment] 2022-05-23 10:42
> using the current default.latex template from pandoc without any changes from [here](https://github.com/jgm/pandoc-templates):

Which version of Pandoc are you using ? `rmarkdown::pandoc_version()`
The Pandoc template usually goes with a Pandoc version. **bookdown** should already be using the default Pandoc template for your version. It would be best to start from this template version

> It seems that somehow the path for the figures produced in the code chunks is messed up during the second LaTeX run, leaving a PDF without any table of contents, cross-references or figures included.

Do you have a more detail example of this ? Can you share a github repo with this so that we can really reproduce ? 
This error `! Undefined control sequence.` usually means that a CTAN package is not loaded while a command is used. 

> includes:
    in_header: preamble.tex

You have custom content here that we don't know about. 

Overall, I need more detailed information to see what the problem is.

**Comment by Woosah** [comment] 2022-05-23 11:37
Hello @cderv,

thank you very much for your help!

`rmarkdown::pandoc_version()` gives 2.17.1.1, which is the version installed alongside `RStudio 2022.2.2.485`.

Reagrding the `preamble_tex` file: No custom content in here, the only line in it is `\usepackage{booktabs}`, which comes as-is from the bookdown project template. As I wrote, I only opened a new Rstudio project using the default bookdown template (New Project -> "Book project using bookdown") which comes pre-installed with the bookdown package, see [here](https://github.com/rstudio/bookdown/blob/main/inst/rstudio/templates/project/resources/common/preamble.tex).
This gives me the following file structure (with the git and Rproj folders ommited here for clarity):

```
.          
├── 01-intro.Rmd
├── 02-cross-refs.Rmd
├── 03-parts.Rmd
├── 04-citations.Rmd
├── 05-blocks.Rmd
├── 06-share.Rmd
├── 07-references.Rmd
├── README.md
├── _bookdown.yml
├── _output.yml
├── book.bib
├── default.latex
├── index.Rmd
├── packages.bib
├── preamble.tex
├── style.css
└── testBook.Rproj
```
Then, without any other changes, I only copy the `default.latex` file from the pandoc repo in here (see also above), and change the content of `_output.yml`: I erase the output for html and epub and add exactly one line to the pdf-output definition:

```
bookdown::pdf_book:
  includes:
    in_header: preamble.tex
  latex_engine: xelatex
  citation_package: natbib
  keep_tex: yes
  template: "default.latex"
```

After that, the error message from above occurs and the directory structure is like that:
```
.
├── 01-intro.Rmd
├── 02-cross-refs.Rmd
├── 03-parts.Rmd
├── 04-citations.Rmd
├── 05-blocks.Rmd
├── 06-share.Rmd
├── 07-references.Rmd
├── README.md
├── _bookdown.yml
├── _bookdown_files
│   └── _main_files
│       └── figure-latex
│           └── nice-fig-1.pdf
├── _main.Rmd
├── _main.log
├── _main.pdf
├── _main.tex
├── _output.yml
├── book.bib
├── default.latex
├── index.Rmd
├── packages.bib
├── preamble.tex
├── style.css
└── testBook.Rproj
```
So you can see here, that after the first LaTeX run, the figure from the code chunk ("nice-fig-1") is in the tex source as 

```
{\centering \includegraphics[width=0.8\linewidth]{_main_files/figure-latex/nice-fig-1} 
```
where the correct path would be `_bookdown_files/_main_files/figure-latex/nice-fig-1`. Therefore, in the next run, the figure is not where it is expected, and the error occures.

I am confused if this is something due to my environment, if it is a bug in bookdown due to a new pandoc version, or whatever...

Here is the complete repo in the state of error, i.e., `_main.log`, `_main.tex` etc. still in there:

https://github.com/Woosah/testBook

Hopefully you have an idea where I can try to find a solution...

Kind regards!

**Comment by cderv** [comment] 2022-05-23 13:20
Ok with **rmarkdown**, we are activating by default this part of the template: 
https://github.com/rstudio/rmarkdown/blob/7eb75a81c7e8ea124b224842c63c19fcaddb8802/R/pdf_document.R#L148-L149

When template is not the default one (as in you case), it is up to the user to activate it. If you add 
````yaml
graphics: true
````
in your `index.Rmd` file, you'll have no issue as the part of the template will be inserted. 

As you are using a custom template, you can also insert that part unconditionally. 

I'll check under what condition Pandoc is activating this variable though

**Comment by cderv** [comment] 2022-05-23 13:26
> I'll check under what condition Pandoc is activating this variable though

I'll remember now. 

Pandoc will activate the graphics part if it detects that some images are included in the document. In the example you ran, images are included using raw LaTeX directly. Pandoc believes that there is no image so it does not activate `graphics = true` leading to no `\usepackage{graphics}` in the template. That is why you need to usg `graphics: true` in YAML, or you need to insert an image using Markdown syntax, so that Pandoc find an image and activate for you. 

So there is no issue, it is just expected behavior - not straightfoward though, but that is how it works when trying to use custom templates. 

Hope it helps

**Closed** 2022-05-23 13:32 UTC
Labels: reprex
