### ISSUE TITLE
Code block is not rendered for epub format

### ISSUE THREAD

**Issue by Colstuwjx** [rstudio/bookdown#908] opened 2020-06-28 03:04 UTC
As the title said, for example, I'm reading the bookdown book, and I found that all the code blocks are not rendered in epub, see the screen capture below:

![image](https://user-images.githubusercontent.com/3972545/85936617-0f543600-b92f-11ea-9496-29421576d289.png)

Is this a known issue? Is there anyway to fix this?
Thanks.

**Comment by Colstuwjx** [comment] 2020-06-28 07:25
And I checked the [pdf version](https://bookdown.org/yihui/bookdown/bookdown.pdf), it seems work well.

**Comment by Colstuwjx** [comment] 2020-06-28 07:52
It seems that the issue was due to the iBooks app..

**Comment by cderv** [comment] 2020-06-28 08:21
When I download the book from the bookdown book site (https://bookdown.org/yihui/bookdown/)
![image](https://user-images.githubusercontent.com/6791940/85942325-c39e8e00-b928-11ea-9a97-6aad89d15be3.png)

I can open it an EPUB reader (Calibre) and I correctly see the code chunk output
![image](https://user-images.githubusercontent.com/6791940/85942366-052f3900-b929-11ea-9d17-400fb3faf4b4.png)

I can't reproduce the issue you see. can you give more details ? (or try another EPUP reader maybe ?)

**Comment by Colstuwjx** [comment] 2020-06-28 08:36
Yes, I think it was an epub-reader related issue. You could try iBooks, I met this issue by iBooks both on macOS and iOS.

**Comment by cderv** [comment] 2021-03-29 21:01
>  I met this issue by iBooks both on macOS and iOS.

I retried by downloading the epub and opening on iBooks in iOS. I don't see the issue you showed in your screenshot. 

I'll close this one as it has been some time and maybe fixed. 

Please open a new issue if there is still some problem with EPUB. 

Thank you.

**Closed by cderv** 2021-03-29 21:01 UTC
