### ISSUE TITLE
R code inside HTML comments is executed

### ISSUE THREAD

**Issue by MJochim** [rstudio/bookdown#471] opened 2017-10-09 17:08 UTC
@raphywink and me were just trying to debug why our book could not be built, when we noticed that commenting out lines in our Rmd files does not have the desired effect. The code inside is still executed.

I have forked bookdown-minimal (see https://github.com/MJochim/bookdown-demo) to illustrate the point.

Let's say you have a document like this:

````
A sample document. With some faulty code integrated:

```{r}
nonExistentFunction()
```

Another paragraph.
````

You notice the code is faulty and want to do away with it. You comment it out:

````
A sample document. With some faulty code integrated:

<!--
```{r}
nonExistentFunction()
```
-->
Another paragraph.
````

Now what I would expect is that the output contains the comment with the literal code inside.

But what happens is, the output contains the comment and inside the comment is the result of the **evaluated faulty code**. In our case, the code errored out and the book could not be built at all.

In my opinion, this behavior is very odd. After all (R)Markdown is supposed to be based on HTML and should therefore respect HTML comments.

---

You are asking to provide information about my R session with the bug report, but I think in this case, they would not be helpful, so I will omit them. If you think otherwise, I can of course add them.

```{r}
devtools::session_info('bookdown')
rmarkdown::pandoc_version()
system('pdflatex --version')
```

**Comment by yihui** [comment] 2017-10-09 18:49
Duplicate of https://github.com/yihui/knitr/issues/1363

**Closed** 2017-11-15 16:13 UTC
