### ISSUE TITLE
Error occurs when there are spaces in Chinese titles

### ISSUE THREAD

**Issue by psychelzh** [rstudio/bookdown#520] opened 2018-01-20 15:10 UTC
I created a simple example with four files (notice the spaces in the header lines):

`index.Rmd`:

```r
---
title: "Untitled"
author: "匿名"
date: "2018年1月20日"
---

# 绪论

这是绪论。
```

`1.Rmd`:

```r
# 第 一
```

`2.Rmd`:

```r
# 第 二
```

`_output.yml`:

```
bookdown::gitbook: default
```

Then I used `bookdown::renderbook("index.Rmd")`, but the following error occured:

```r
Error in split_chapters(output, gitbook_page, number_sections, split_by,  : 
  Automatically generated filenames contain duplicated ones: -
Please delete _main.Rmd after you finish debugging the error.
```

When I delete spaces from those headers, there is nothing wrong. I guess the filename automatic generation rule is a little buggy.

**Comment by psychelzh** [comment] 2018-01-20 15:23
Then I found an option: `split_by`. I cound set it as another value (e.g., "none") to solve this problem. But the default behavior would be a little buggy.

**Comment by yihui** [comment] 2018-01-20 15:30
Duplicate of https://github.com/rstudio/rmarkdown/issues/1149

**Comment by yihui** [comment] 2018-01-20 15:31
Although it may not be easy for you to realize that this issue is the same as https://github.com/rstudio/rmarkdown/issues/1149, it is still because Pandoc cannot generate appropriate automatic IDs for section titles. You must manually assign IDs to them.

**Closed by yihui** 2018-01-20 15:31 UTC

**Comment by psychelzh** [comment] 2018-01-20 15:33
I'd better use "split_by" option to solve this problem. Is it right?

**Comment by yihui** [comment] 2018-01-20 15:46
It depends on what you mean by "solve". If you only want to avoid the error, `split_by = 'none'` can do it. If you want to split the book by sections or chapters, you have to manually assign IDs to titles as I mentioned above.

**Comment by psychelzh** [comment] 2018-01-21 03:03
Thank you for your quick response. I understand it now.
