### ISSUE TITLE
Code block in rmdnote needs margins adjusted

### ISSUE THREAD

**Issue by hadley** [rstudio/bookdown#1084] opened 2021-02-22 13:32 UTC
e.g.

<img width="522" alt="Screenshot 2021-02-22 at 7 32 37 AM" src="https://user-images.githubusercontent.com/4196/108715194-23612f00-74e0-11eb-8588-1e858f4e0dce.png">

Code should occupy full width of block

**Comment by cderv** [comment] 2021-06-02 14:03
@maelle @apreshill I would also deal with this as it could be just a small piece of CSS to add.

**Comment by maelle** [comment] 2021-06-14 11:30
Source https://github.com/hadley/mastering-shiny/blob/0628a35189c62f9bba3814388d9c844a172cd211/scaling-modules.Rmd#L153
Live version https://mastering-shiny.org/scaling-modules.html?q=overhaul#updated-app

**Comment by cderv** [comment] 2021-06-14 13:45
@hadley can you add precision on the expected result please ? 

The screenshot looks like the current behavior (from the link above) so it seems this is not the expected behavior (unless this has already been fixed in the book since you opened the issue). 

This would help us know what to do for sure as I don't think the current PR proposal is the correct understanding of this. 

Thank you.

**Comment by hadley** [comment] 2021-06-14 19:30
Like how code blocks on a narrow page occupy the full width of the column, the code block within a note should also occupy the full width (i.e. no gap between left and right side of code block and containing border). Does that make sense? It's not easy to describe in words.

**Comment by cderv** [comment] 2021-06-14 19:34
> (i.e. no gap between left and right side of code block and containing border)

Yes this makes sense and confirms my first understanding. I now have the expected result in mind. Thanks !

@maelle is that ok for you ?

**Comment by cderv** [comment] 2021-06-29 14:48
This will now look like this.

![image](https://user-images.githubusercontent.com/6791940/123819024-bfb99900-d8f9-11eb-8aa4-fac3cbc717ab.png)

**Closed** 2021-06-29 14:51 UTC
Labels: bs4_book :hiking_boot:, feature, next

**Comment by hadley** [comment] 2021-06-29 18:40
Looks good!
