### ISSUE TITLE
No caption for table with only one column

### ISSUE THREAD

**Issue by benmarwick** [rstudio/bookdown#494] opened 2017-11-28 23:24 UTC
Here's the MWE:
````
---
output: bookdown::html_document2
---

Table \@ref(tab:onecol)

```{r onecol}
knitr::kable(data.frame(x = 1:2), caption = "One col table")
```

Table \@ref(tab:twocol)

```{r twocol}
knitr::kable(data.frame(x = 1:2, y = 1:2), caption = "Two col table")
```
````
Here's the output:

![mwe](https://user-images.githubusercontent.com/1262179/33349619-bf1d80ea-d44f-11e7-91b4-4c597e755268.png)

Here are my settings:

```
> devtools::session_info('bookdown')
Session info -------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, mingw32             
 ui       RStudio (1.1.381)           
 language (EN)                        
 collate  English_Australia.1252      
 tz       America/Los_Angeles         
 date     2017-11-28                  

Packages -----------------------------------------------------------------------
 package   * version date       source                           
 backports   1.1.1   2017-09-25 CRAN (R 3.4.1)                   
 base64enc   0.1-3   2015-07-28 CRAN (R 3.4.0)                   
 bookdown    0.5.10  2017-11-28 Github (rstudio/bookdown@d78c661)
 digest      0.6.12  2017-01-27 CRAN (R 3.4.0)                   
 evaluate    0.10.1  2017-06-24 CRAN (R 3.4.0)                   
 graphics  * 3.4.1   2017-06-30 local                            
 grDevices * 3.4.1   2017-06-30 local                            
 highr       0.6     2016-05-09 CRAN (R 3.4.0)                   
 htmltools   0.3.6   2017-04-28 CRAN (R 3.4.0)                   
 jsonlite    1.5     2017-06-01 CRAN (R 3.4.0)                   
 knitr       1.17    2017-08-10 CRAN (R 3.4.1)                   
 magrittr    1.5     2014-11-22 CRAN (R 3.4.0)                   
 markdown    0.8     2017-04-20 CRAN (R 3.4.0)                   
 methods   * 3.4.1   2017-06-30 local                            
 mime        0.5     2016-07-07 CRAN (R 3.4.0)                   
 Rcpp        0.12.13 2017-09-28 CRAN (R 3.4.2)                   
 rmarkdown   1.8     2017-11-17 CRAN (R 3.4.2)                   
 rprojroot   1.2     2017-01-16 CRAN (R 3.4.0)                   
 stats     * 3.4.1   2017-06-30 local                            
 stringi     1.1.6   2017-11-17 CRAN (R 3.4.2)                   
 stringr     1.2.0   2017-02-18 CRAN (R 3.4.0)                   
 tools       3.4.1   2017-06-30 local                            
 utils     * 3.4.1   2017-06-30 local                            
 yaml        2.1.14  2016-11-12 CRAN (R 3.4.0) 
> rmarkdown::pandoc_version()
[1] ‘1.19.2.1’
```

**Comment by yihui** [comment] 2017-11-29 05:13
Sounds like a duplicate of yihui/knitr#1460 . Please test the development version of knitr:

```r
devtools::install_github('yihui/knitr')
```

**Closed** 2017-12-28 21:16 UTC
