### ISSUE TITLE
split_by: section option for bs4_book theme

### ISSUE THREAD

**Issue by kylebutts** [rstudio/bookdown#1048] opened 2020-12-19 17:12 UTC
Hi there, I'm using the bs4_book theme which looks wonderful. I am wondering if it's possible to include the split_by option used in the `gitbook` theme to separate html pages by section instead of by chapter.

**Comment by cderv** [comment] 2020-12-21 14:00
As the doc of `bs4_book` mentions
> This theme is designed for books that use one chapter per page.

We currently do not plan to change this limitation which is by designed in this book format. I leave this issue open as a reminder in case we ever reconsider.

**Comment by Emmanuelle7** [comment] 2021-01-22 12:55
Hello, thanks for the bookdown package! I have also come across this issue and would like to request a reconsideration to enable splitting by section as well.

**Comment by cderv** [comment] 2021-01-22 16:04
@hadley I recall this is design choice of `bs4_book()`. Is the splitting by chapter hardly link to the format or is it something we could consider in the future ?

**Comment by hadley** [comment] 2021-01-22 16:32
I think it's out of scope for `bs4_book()` — it's a deliberate decision to tie the input file structure to the output file structure, and I believe strongly that it's necessary in order to provide a polished user experience. (That said, in the future I think we should consider another output type specifically designed around the needs of one section per page.)

**Closed by hadley** 2021-01-22 16:32 UTC
Labels: bs4_book :hiking_boot:, enhancement
