### ISSUE TITLE
TOC depth int bs4_book

### ISSUE THREAD

**Issue by karlmay88** [rstudio/bookdown#1377] opened 2022-08-31 02:07 UTC
Hi there,

I am wondering whether there is a way to increase the TOC depth in bs4_book? It looks as if my current toc setting do not have any effect. This is the content of `_output.yml`
```
bookdown::bs4_book:
  toc_depth: 6
  theme:
    primary: "#0d6efd"   
       base_font: 
      google: Sen
    heading_font:
      google:
        family: Bitter
        wght: 200
    code_font:
      google: 
        # arguments to sass::font_google() 
        family: DM Mono
        local: false
```

**Comment by cderv** [comment] 2022-08-31 08:58
`toc_depth` is not part of the customization possible for `bs4_book`format. Related issue one year ago: https://github.com/rstudio/bookdown/issues/1254

This is by design for this format as it would be hard to give a nice formatting for more than 3 levels 
https://github.com/rstudio/bookdown/blob/7ce6dc65b39ffe846e2ff88c160a69f2348a5a92/R/bs4_book.R#L134-L138

BTW `toc` is not a supported argument in `bs4_book` and setting `toc_depth` should have thrown an error. I'll fix that.

**Comment by cderv** [comment] 2022-08-31 09:29
I am closing and tracking the idea for votes in https://github.com/rstudio/bookdown/issues/1378 

Also, it will throw an error in next version of **bookdown** to set `toc_depth` so that it is clear that it is not allowed as it does not work. 

thank you !

**Closed by cderv** 2022-08-31 09:29 UTC
