### ISSUE TITLE
Unnumbering headings not working in PDF for H5, H6

### ISSUE THREAD

**Issue by mterente** [rstudio/bookdown#516] opened 2018-01-18 10:46 UTC
Hi, 

Unnnumbering for H5 and H6 doesn't work in the exported PDF.
To reproduce:

````
# Heading 1 {-}

## Heading 2 {-}

### Heading 3 {-}

#### Heading 4 {-}

##### Heading 5 {-}

###### Heading 6 {-}

####### Heading 7 {-}
````

Output:

![image](https://user-images.githubusercontent.com/15198855/35094017-572983ea-fc44-11e7-8f66-844b616e6dbc.png)

I tried also with 
```
##### Heading 5 {.unnumbered}

###### Heading 6 {.unnumbered}
```
and still it doesn't work.

The minimal reproducible example attached:
[bookdown-minimal.zip](https://github.com/rstudio/bookdown/files/1642533/bookdown-minimal.zip)

Thanks, 
Mihai

**Comment by yihui** [comment] 2018-01-18 15:27
Duplicate of #493

**Closed by yihui** 2018-01-18 15:27 UTC
Labels: duplicate
