### ISSUE TITLE
R notebook examples in bookdown

### ISSUE THREAD

**Issue by mbanghart** [rstudio/bookdown#652] opened 2018-11-17 16:37 UTC
Could there be some means to allow examples done in bookdown to also be available to readers in an R notebook form.  This would allow users of a book to quickly interact with the material of the book.  Thanks for considering this request.

**Comment by cderv** [comment] 2021-03-24 10:21
I believe this is related to https://github.com/rstudio/bookdown/issues/851 and we'll keep this one.

Please reopen with more details if the other feature request is not what you meant.

Thank you.

**Comment by cderv** [comment] 2021-03-24 10:21
Duplicate of #851

**Closed by cderv** 2021-03-24 10:21 UTC
