### ISSUE TITLE
bookdown::serve_book() URL-server slowly work

### ISSUE THREAD

**Issue by avraam-1997** [rstudio/bookdown#1059] opened 2021-01-11 12:44 UTC
Hi! The bookdown::serv_book() function starts a URL server that is running VERY slowly. I use Windows. How can I speed up its work?

![image](https://user-images.githubusercontent.com/52919010/104186695-db061a00-5427-11eb-88c8-3c7163686d5d.png)

**Comment by cderv** [comment] 2021-01-11 12:49
Are you running the function on a bookdown project ? 
What I mean is running `serve_book()` only a folder (and subfolders) that are containing the book ? 

Also, is the book a particularly big one, with a wide number of files ? Or with many files some of them not related to the book ? 

I am trying to isolate some specificity of your usage in order to better understand what could happen. Thank you

**Comment by avraam-1997** [comment] 2021-01-11 13:04
Hi cderv, Thanks for your attention

> Are you running the function on a bookdown project ?

Of course)

> What I mean is running `serve_book()` only a folder (and subfolders) that are containing the book ?

Yes. My _bookdown.yml includes pointing to folders with Rmd files for the workbook. Nothing superfluous.

> Also, is the book a particularly big one, with a wide number of files ? Or with many files some of them not related to the book 

Everything is relative.
1) Building a book with the "Build" button takes 2-4 seconds
2) About 100 screenshotes and <20 files for download via book

**Comment by cderv** [comment] 2021-01-11 14:01
`bookdown::serve_book()` should by default only re-rendered for Rmd to HTML the modified file. It should allow to preview your book easily. 

If you have a lot of computation in your Rmd file, the rendering can take time. Otherwise, if you have a lot of JS dependencies or other component that requires load time in the browser, this could also be a source of delay. 

If the slow rendering you encounter is in the browser (and not really during R rendering), you can try to investigate using the Developper Tools of your brower to identify which part of your HTML file takes time loading. 

For example with chrome, you can look at network activity and load time: https://developers.google.com/web/tools/chrome-devtools/network

This is some hints in order for you to precise what could happen

**Comment by cderv** [comment] 2021-03-31 10:06
Have you looked at the Network activity in your browser developer tools ?

As said before, it could be something specific to your book and your setup. We'll be happy to look into it if you can provide a reproducible example or more informations that would less us know where to look. 

As there was no other report of such slow working of `serve_book()` and no answer since my last comment, I'll close this. 

Please reopen if this is still something that is happening. Thank you!

**Closed by cderv** 2021-03-31 10:06 UTC
Labels: question
