### ISSUE TITLE
bookdown::publish_book from travis

### ISSUE THREAD

**Issue by jumpingrivers** [rstudio/bookdown#237] opened 2016-10-31 21:47 UTC
Can you give a hint on how to run publish_book from travis?

**Comment by yihui** [comment] 2016-11-01 04:58
That sounds like a good idea, but I don't know the answer. I'll ask the team and get back to you.

**Comment by cderv** [comment] 2021-03-18 13:16
Related to https://github.com/rstudio/bookdown/issues/1075 and I think will be done there with an example from Github Action. 

Closing in favor of https://github.com/rstudio/bookdown/issues/1075

**Comment by cderv** [comment] 2021-03-18 13:16
Duplicate of #1075

**Closed by cderv** 2021-03-18 13:16 UTC
